# Generated by Django 4.2.7 on 2023-12-19 16:02

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BikeStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("station_name", models.CharField(max_length=100)),
                ("parking_bike_count", models.IntegerField()),
                ("total_rack_count", models.IntegerField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="PredictionBicycle",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("station_name", models.CharField(max_length=100)),
                ("rental_date", models.CharField()),
                ("rental_hour", models.IntegerField()),
                ("expected_usage", models.IntegerField()),
                ("temperature", models.IntegerField()),
                ("wind_speed", models.IntegerField()),
                ("rainfall", models.FloatField()),
                ("humidity", models.IntegerField()),
                ("day_of_week", models.JSONField()),
            ],
            options={
                "db_table": "prediction_bicycle",
            },
        ),
    ]
